/**
 * Contract guard for public/data/aliyot.json (generated by
 * scripts/generate-aliyot.js from @hebcal/leyning + src/data/parshiyot.js).
 *
 * Shape: { [route]: { book, aliyot: [{ n, start:[perek,pasuk], end:[perek,pasuk], verseCount }], total } }
 * perek/pasuk are 0-indexed. Runs against the real generated file, not a
 * fixture, so it doubles as a regression check on the generator's output.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import parshiyot from '../src/data/parshiyot.js'

const aliyot = JSON.parse(readFileSync(new URL('../public/data/aliyot.json', import.meta.url), 'utf8'))

const BOOKS = ['bereishit', 'shmot', 'vayikra', 'bamidbar', 'dvarim']
const chapterLengths = {}
for (const book of BOOKS) {
  const torah = JSON.parse(readFileSync(new URL(`../public/data/torah/${book}.json`, import.meta.url), 'utf8'))
  chapterLengths[book] = torah.text.map(ch => ch.length)
}

function ordinal(book, [perek, pasuk]) {
  const lens = chapterLengths[book]
  let n = 0
  for (let i = 0; i < perek; i++) n += lens[i]
  return n + pasuk
}

const routes = Object.keys(parshiyot)

describe('public/data/aliyot.json', () => {
  it('has all 61 parshiyot.js routes, and no extra routes', () => {
    expect(routes.length).toBe(61)
    for (const route of routes) {
      expect(aliyot[route], `missing route ${route}`).toBeDefined()
    }
    for (const route of Object.keys(aliyot)) {
      expect(parshiyot[route], `extra route ${route} not in parshiyot.js`).toBeDefined()
    }
  })

  it('book matches def.chumash for every route', () => {
    for (const route of routes) {
      expect(aliyot[route].book, route).toBe(parshiyot[route].chumash)
    }
  })

  it('aliyot[0].start equals def.start, and last end equals def.end', () => {
    for (const route of routes) {
      const def = parshiyot[route]
      const al = aliyot[route].aliyot
      expect(al[0].start, `${route} start`).toEqual(def.start)
      expect(al[al.length - 1].end, `${route} end`).toEqual(def.end)
    }
  })

  it('every aliyah is contiguous with the previous one, across chapter boundaries', () => {
    for (const route of routes) {
      const entry = aliyot[route]
      const al = entry.aliyot
      for (let i = 1; i < al.length; i++) {
        const prevEnd = ordinal(entry.book, al[i - 1].end)
        const start = ordinal(entry.book, al[i].start)
        expect(start, `${route} aliyah ${i + 1} vs ${i}`).toBe(prevEnd + 1)
      }
    }
  })

  it('sum(verseCount) === total === corpus verse count for every route', () => {
    for (const route of routes) {
      const def = parshiyot[route]
      const entry = aliyot[route]
      const sum = entry.aliyot.reduce((s, a) => s + a.verseCount, 0)
      const corpusCount = ordinal(entry.book, def.end) - ordinal(entry.book, def.start) + 1
      expect(sum, `${route} sum(verseCount)`).toBe(entry.total)
      expect(entry.total, `${route} total vs corpus`).toBe(corpusCount)
    }
  })

  it('each aliyah verseCount matches its own start/end ordinals', () => {
    for (const route of routes) {
      const entry = aliyot[route]
      for (const a of entry.aliyot) {
        const count = ordinal(entry.book, a.end) - ordinal(entry.book, a.start) + 1
        expect(count, `${route} aliyah ${a.n}`).toBe(a.verseCount)
      }
    }
  })

  it('n is 1..length for every route', () => {
    for (const route of routes) {
      const al = aliyot[route].aliyot
      al.forEach((a, i) => {
        expect(a.n, `${route} aliyot[${i}].n`).toBe(i + 1)
      })
    }
  })

  it('bereshit aliyot[0] matches the known hand-check', () => {
    expect(aliyot.bereshit.aliyot[0]).toEqual({ n: 1, start: [0, 0], end: [1, 2], verseCount: 34 })
  })

  it('bereshit aliyot[6].end is [5,7]', () => {
    expect(aliyot.bereshit.aliyot[6].end).toEqual([5, 7])
  })

  it('matot-masei exists with aliyot[0].start [29,1] and last end [35,12]', () => {
    const entry = aliyot['matot-masei']
    expect(entry).toBeDefined()
    expect(entry.aliyot[0].start).toEqual([29, 1])
    expect(entry.aliyot[entry.aliyot.length - 1].end).toEqual([35, 12])
  })

  it('vzot-haberachah last end is [33,11]', () => {
    const entry = aliyot['vzot-haberachah']
    expect(entry.aliyot[entry.aliyot.length - 1].end).toEqual([33, 11])
  })
})
